services:
  db:
    image: mysql:8.4
    container_name: fiap_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fiap_vehicles
      MYSQL_USER: fiap
      MYSQL_PASSWORD: fiap
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
  api:
    build: .
    container_name: fiap_api
    env_file:
      - .env
    environment:
      DB_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "python main.py"]
volumes:
  db_data:
